version: 0.2
phases:
  pre_build:
    commands:
      - echo "Running pre_build stage..."
  build:
    commands:
      - echo "Test and building application..."
      - mvn clean test compile war:war
  post_build:
    commands:
      - echo "Moving files to upload..."
      - mv target/*.war ./ROOT.war
artifacts:
  files:
    - ROOT.war